### ISSUE TITLE
Qiymetlendirme

### ISSUE THREAD

**Issue by EshginKazimov** [eemaharramli/Console-App-Pharmacy#1]
Ela! Dushuncen chox eladi! Sadece gelecek uchun bir iki comment bildirecem. Language sechenen sonra herdefe parametrde gondermek yerine, static bir classda saxlasan sechilmish neticeni, ve hami hemen class-dan goturse currentLanguage daha yaxshi olardi, bir nov Store mentigi duzeldirsen, programin settingleri o store-da qalir. Birdeki Dictionary duzeltmisen olarin keylerini birbasha stringnen verme chunki mexaniki sehvler emele gelecek, enum istifade ede bilersen ve ya yenede yeni static bir class-da const fieldler saxlaya bilersen string formasinda. Ugurlar sene!
100 bal

**Comment by eemaharramli** [comment]
Teshekkur edirem Eshqin muellim. In shaa Allah yeniden dersleriniz bashlayanda commentlerivizi gostersez chox shad olacam. Bu dil baresinde ilk once demek olar ki hechne bilmemeyime baxmayaragh bu dili sevdirdiz)

**Comment by EshginKazimov** [comment]
Gosterecem inshAllah. Hershey yaxshi olacaq sen barede, ugurlar sene!
